version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Use environment variable
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Use environment variable
      MYSQL_USER: ${MYSQL_USER}                    # Use environment variable
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Use environment variable
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    command: --bind-address=0.0.0.0
    networks:
      - db-network
networks:
  db-network:
volumes:
  mariadb_data:
