version: '3.8'
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  st-mnm-fe:
    build:
      context: ./st-mnm-fe
    container_name: st-mnm-fe
    ports:
      - "80:80"
  st-mnm-be:
    build:
      context: ./st-mnm-be
    container_name: st-mnm-be
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/student?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
